# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa
                ('education', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='people',
            field=models.ManyToManyField(to='education_data.People'),
        ),
    ]
