# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def forwards(self, orm):
        "Write your forwards methods here."
        from django.core.management import call_command
        call_command("loaddata", "initial_data.json")

    dependencies = [
        ('education_data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
