# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    
    def forwards(self, orm):
        "Write your forwards methods here."
        from django.core.management import call_command
        call_command("loaddata", "currency_init_data.json")
    
    dependencies = [
        ('education_data', '0002_load_fixtures'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_short_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.RunPython(forwards)
    ]
